name: chart_app
description: Chart App
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=3.3.3 <4.0.0"
    flutter: "3.24.1"

dependencies:
    flutter:
        sdk: flutter
    deriv_chart:
        git:
            url: https://github.com/deriv-com/flutter-chart.git
            ref: 71bded4a844ac458d478e8f03b5b7cbf6ab87a41
    web: ^1.1.1

dev_dependencies:
    deriv_lint:
        git:
            url: https://github.com/deriv-com/flutter-deriv-packages.git
            path: packages/deriv_lint
            ref: dev
    flutter_test:
        sdk: flutter

flutter:
    fonts:
        - family: IBMPlexSans
          fonts:
              - asset: fonts/IBMPlexSans-Regular.ttf
              - asset: fonts/IBMPlexSans-Bold.ttf
                weight: 700
    uses-material-design: true
